Style/ClassVars:
 Enabled: false

Metrics/MethodLength:
 Enabled: false

Metrics/AbcSize:
 Enabled: false

Metrics/PerceivedComplexity:
 Enabled: false

Metrics/CyclomaticComplexity:
 Enabled: false

